<?php
$currencies['AED'] = array ( 'code' => 784, 'decimal' => 2, 'name' => "United Arab Emirates dirham" );
$currencies['AFN'] = array ( 'code' => 971, 'decimal' => 2, 'name' => "Afghani" );
$currencies['ALL'] = array ( 'code' => 008, 'decimal' => 2, 'name' => "Lek" );
$currencies['AMD'] = array ( 'code' => 051, 'decimal' => 0, 'name' => "Armenian dram" );
$currencies['ANG'] = array ( 'code' => 532, 'decimal' => 2, 'name' => "Netherlands Antillean guilder" );
$currencies['AOA'] = array ( 'code' => 973, 'decimal' => 1, 'name' => "Kwanza" );
$currencies['ARS'] = array ( 'code' => 032, 'decimal' => 2, 'name' => "Argentine peso" );
$currencies['AUD'] = array ( 'code' => 036, 'decimal' => 2, 'name' => "Australian dollar" );
$currencies['AWG'] = array ( 'code' => 533, 'decimal' => 2, 'name' => "Aruban guilder" );
$currencies['AZN'] = array ( 'code' => 944, 'decimal' => 2, 'name' => "Azerbaijanian manat" );
$currencies['BAM'] = array ( 'code' => 977, 'decimal' => 2, 'name' => "Convertible marks" );
$currencies['BBD'] = array ( 'code' => 052, 'decimal' => 2, 'name' => "Barbados dollar" );
$currencies['BDT'] = array ( 'code' => 050, 'decimal' => 2, 'name' => "Bangladeshi taka" );
$currencies['BGN'] = array ( 'code' => 975, 'decimal' => 2, 'name' => "Bulgarian lev" );
$currencies['BHD'] = array ( 'code' => 048, 'decimal' => 3, 'name' => "Bahraini dinar" );
$currencies['BIF'] = array ( 'code' => 108, 'decimal' => 0, 'name' => "Burundian franc" );
$currencies['BMD'] = array ( 'code' => 060, 'decimal' => 2, 'name' => "Bermudian dollar (customarily known as Bermuda dollar)" );
$currencies['BND'] = array ( 'code' => 096, 'decimal' => 2, 'name' => "Brunei dollar" );
$currencies['BOB'] = array ( 'code' => 068, 'decimal' => 2, 'name' => "Boliviano" );
$currencies['BOV'] = array ( 'code' => 984, 'decimal' => 2, 'name' => "Bolivian Mvdol (funds code)" );
$currencies['BRL'] = array ( 'code' => 986, 'decimal' => 2, 'name' => "Brazilian real" );
$currencies['BSD'] = array ( 'code' => 044, 'decimal' => 2, 'name' => "Bahamian dollar" );
$currencies['BTN'] = array ( 'code' => 064, 'decimal' => 2, 'name' => "Ngultrum" );
$currencies['BWP'] = array ( 'code' => 072, 'decimal' => 2, 'name' => "Pula" );
$currencies['BYR'] = array ( 'code' => 974, 'decimal' => 0, 'name' => "Belarussian ruble" );
$currencies['BZD'] = array ( 'code' => 084, 'decimal' => 2, 'name' => "Belize dollar" );
$currencies['CAD'] = array ( 'code' => 124, 'decimal' => 2, 'name' => "Canadian dollar" );
$currencies['CDF'] = array ( 'code' => 976, 'decimal' => 2, 'name' => "Franc Congolais" );
$currencies['CHE'] = array ( 'code' => 947, 'decimal' => 2, 'name' => "WIR euro (complementary currency)" );
$currencies['CHF'] = array ( 'code' => 756, 'decimal' => 2, 'name' => "Swiss franc" );
$currencies['CHW'] = array ( 'code' => 948, 'decimal' => 2, 'name' => "WIR franc (complementary currency)" );
$currencies['CLF'] = array ( 'code' => 990, 'decimal' => 0, 'name' => "Unidad de Fomento (funds code)" );
$currencies['CLP'] = array ( 'code' => 152, 'decimal' => 0, 'name' => "Chilean peso" );
$currencies['CNY'] = array ( 'code' => 156, 'decimal' => 1, 'name' => "Chinese Yuan" );
$currencies['COP'] = array ( 'code' => 170, 'decimal' => 0, 'name' => "Colombian peso" );
$currencies['COU'] = array ( 'code' => 970, 'decimal' => 2, 'name' => "Unidad de Valor Real" );
$currencies['CRC'] = array ( 'code' => 188, 'decimal' => 2, 'name' => "Costa Rican colon" );
$currencies['CUC'] = array ( 'code' => 931, 'decimal' => 2, 'name' => "Cuban convertible peso" );
$currencies['CUP'] = array ( 'code' => 192, 'decimal' => 2, 'name' => "Cuban peso" );
$currencies['CVE'] = array ( 'code' => 132, 'decimal' => 2, 'name' => "Cape Verde escudo" );
$currencies['CZK'] = array ( 'code' => 203, 'decimal' => 2, 'name' => "Czech Koruna" );
$currencies['DJF'] = array ( 'code' => 262, 'decimal' => 0, 'name' => "Djibouti franc" );
$currencies['DKK'] = array ( 'code' => 208, 'decimal' => 2, 'name' => "Danish krone" );
$currencies['DOP'] = array ( 'code' => 214, 'decimal' => 2, 'name' => "Dominican peso" );
$currencies['DZD'] = array ( 'code' => 012, 'decimal' => 2, 'name' => "Algerian dinar" );
$currencies['EEK'] = array ( 'code' => 233, 'decimal' => 2, 'name' => "Kroon" );
$currencies['EGP'] = array ( 'code' => 818, 'decimal' => 2, 'name' => "Egyptian pound" );
$currencies['ERN'] = array ( 'code' => 232, 'decimal' => 2, 'name' => "Nakfa" );
$currencies['ETB'] = array ( 'code' => 230, 'decimal' => 2, 'name' => "Ethiopian birr" );
$currencies['EUR'] = array ( 'code' => 978, 'decimal' => 2, 'name' => "euro" );
$currencies['FJD'] = array ( 'code' => 242, 'decimal' => 2, 'name' => "Fiji dollar" );
$currencies['FKP'] = array ( 'code' => 238, 'decimal' => 2, 'name' => "Falkland Islands pound" );
$currencies['GBP'] = array ( 'code' => 826, 'decimal' => 2, 'name' => "Pound sterling" );
$currencies['GEL'] = array ( 'code' => 981, 'decimal' => 2, 'name' => "Lari" );
$currencies['GHS'] = array ( 'code' => 936, 'decimal' => 2, 'name' => "Cedi" );
$currencies['GIP'] = array ( 'code' => 292, 'decimal' => 2, 'name' => "Gibraltar pound" );
$currencies['GMD'] = array ( 'code' => 270, 'decimal' => 2, 'name' => "Dalasi" );
$currencies['GNF'] = array ( 'code' => 324, 'decimal' => 0, 'name' => "Guinea franc" );
$currencies['GTQ'] = array ( 'code' => 320, 'decimal' => 2, 'name' => "Quetzal" );
$currencies['GYD'] = array ( 'code' => 328, 'decimal' => 2, 'name' => "Guyana dollar" );
$currencies['HKD'] = array ( 'code' => 344, 'decimal' => 1, 'name' => "Hong Kong dollar" );
$currencies['HNL'] = array ( 'code' => 340, 'decimal' => 2, 'name' => "Lempira" );
$currencies['HRK'] = array ( 'code' => 191, 'decimal' => 2, 'name' => "Croatian kuna" );
$currencies['HTG'] = array ( 'code' => 332, 'decimal' => 2, 'name' => "Haiti gourde" );
$currencies['HUF'] = array ( 'code' => 348, 'decimal' => 0, 'name' => "Forint" );
$currencies['IDR'] = array ( 'code' => 360, 'decimal' => 0, 'name' => "Rupiah" );
$currencies['ILS'] = array ( 'code' => 376, 'decimal' => 2, 'name' => "Israeli new sheqel" );
$currencies['INR'] = array ( 'code' => 356, 'decimal' => 2, 'name' => "Indian rupee" );
$currencies['IQD'] = array ( 'code' => 368, 'decimal' => 0, 'name' => "Iraqi dinar" );
$currencies['IRR'] = array ( 'code' => 364, 'decimal' => 0, 'name' => "Iranian rial" );
$currencies['ISK'] = array ( 'code' => 352, 'decimal' => 0, 'name' => "Iceland krona" );
$currencies['JMD'] = array ( 'code' => 388, 'decimal' => 2, 'name' => "Jamaican dollar" );
$currencies['JOD'] = array ( 'code' => 400, 'decimal' => 3, 'name' => "Jordanian dinar" );
$currencies['JPY'] = array ( 'code' => 392, 'decimal' => 0, 'name' => "Japanese yen" );
$currencies['KES'] = array ( 'code' => 404, 'decimal' => 2, 'name' => "Kenyan shilling" );
$currencies['KGS'] = array ( 'code' => 417, 'decimal' => 2, 'name' => "Som" );
$currencies['KHR'] = array ( 'code' => 116, 'decimal' => 0, 'name' => "Riel" );
$currencies['KMF'] = array ( 'code' => 174, 'decimal' => 0, 'name' => "Comoro franc" );
$currencies['KPW'] = array ( 'code' => 408, 'decimal' => 0, 'name' => "North Korean won" );
$currencies['KRW'] = array ( 'code' => 410, 'decimal' => 0, 'name' => "South Korean won" );
$currencies['KWD'] = array ( 'code' => 414, 'decimal' => 3, 'name' => "Kuwaiti dinar" );
$currencies['KYD'] = array ( 'code' => 136, 'decimal' => 2, 'name' => "Cayman Islands dollar" );
$currencies['KZT'] = array ( 'code' => 398, 'decimal' => 2, 'name' => "Tenge" );
$currencies['LAK'] = array ( 'code' => 418, 'decimal' => 0, 'name' => "Kip" );
$currencies['LBP'] = array ( 'code' => 422, 'decimal' => 0, 'name' => "Lebanese pound" );
$currencies['LKR'] = array ( 'code' => 144, 'decimal' => 2, 'name' => "Sri Lanka rupee" );
$currencies['LRD'] = array ( 'code' => 430, 'decimal' => 2, 'name' => "Liberian dollar" );
$currencies['LSL'] = array ( 'code' => 426, 'decimal' => 2, 'name' => "Lesotho loti" );
$currencies['LTL'] = array ( 'code' => 440, 'decimal' => 2, 'name' => "Lithuanian litas" );
$currencies['LVL'] = array ( 'code' => 428, 'decimal' => 2, 'name' => "Latvian lats" );
$currencies['LYD'] = array ( 'code' => 434, 'decimal' => 3, 'name' => "Libyan dinar" );
$currencies['MAD'] = array ( 'code' => 504, 'decimal' => 2, 'name' => "Moroccan dirham" );
$currencies['MDL'] = array ( 'code' => 498, 'decimal' => 2, 'name' => "Moldovan leu" );
$currencies['MGA'] = array ( 'code' => 969, 'decimal' => 0.7, 'name' => "Malagasy ariary" );
$currencies['MKD'] = array ( 'code' => 807, 'decimal' => 2, 'name' => "Denar" );
$currencies['MMK'] = array ( 'code' => 104, 'decimal' => 0, 'name' => "Kyat" );
$currencies['MNT'] = array ( 'code' => 496, 'decimal' => 2, 'name' => "Tugrik" );
$currencies['MOP'] = array ( 'code' => 446, 'decimal' => 1, 'name' => "Pataca" );
$currencies['MRO'] = array ( 'code' => 478, 'decimal' => 0.7, 'name' => "Ouguiya" );
$currencies['MUR'] = array ( 'code' => 480, 'decimal' => 2, 'name' => "Mauritius rupee" );
$currencies['MVR'] = array ( 'code' => 462, 'decimal' => 2, 'name' => "Rufiyaa" );
$currencies['MWK'] = array ( 'code' => 454, 'decimal' => 2, 'name' => "Kwacha" );
$currencies['MXN'] = array ( 'code' => 484, 'decimal' => 2, 'name' => "Mexican peso", 'symbol' => array( 'decimal' => '.', 'group' => ',', 'symbol' => '$' ) );
$currencies['MXV'] = array ( 'code' => 979, 'decimal' => 2, 'name' => "Mexican Unidad de Inversion (UDI) (funds code)" );
$currencies['MYR'] = array ( 'code' => 458, 'decimal' => 2, 'name' => "Malaysian ringgit" );
$currencies['MZN'] = array ( 'code' => 943, 'decimal' => 2, 'name' => "Metical" );
$currencies['NAD'] = array ( 'code' => 516, 'decimal' => 2, 'name' => "Namibian dollar" );
$currencies['NGN'] = array ( 'code' => 566, 'decimal' => 2, 'name' => "Naira" );
$currencies['NIO'] = array ( 'code' => 558, 'decimal' => 2, 'name' => "Cordoba oro" );
$currencies['NOK'] = array ( 'code' => 578, 'decimal' => 2, 'name' => "Norwegian krone" );
$currencies['NPR'] = array ( 'code' => 524, 'decimal' => 2, 'name' => "Nepalese rupee" );
$currencies['NZD'] = array ( 'code' => 554, 'decimal' => 2, 'name' => "New Zealand dollar" );
$currencies['OMR'] = array ( 'code' => 512, 'decimal' => 3, 'name' => "Ri'al Omani" );
$currencies['PAB'] = array ( 'code' => 590, 'decimal' => 2, 'name' => "Balboa" );
$currencies['PEN'] = array ( 'code' => 604, 'decimal' => 2, 'name' => "Nuevo sol" );
$currencies['PGK'] = array ( 'code' => 598, 'decimal' => 2, 'name' => "Kina" );
$currencies['PHP'] = array ( 'code' => 608, 'decimal' => 2, 'name' => "Philippine peso" );
$currencies['PKR'] = array ( 'code' => 586, 'decimal' => 2, 'name' => "Pakistan rupee" );
$currencies['PLN'] = array ( 'code' => 985, 'decimal' => 2, 'name' => "Złoty" );
$currencies['PYG'] = array ( 'code' => 600, 'decimal' => 0, 'name' => "Guarani" );
$currencies['QAR'] = array ( 'code' => 634, 'decimal' => 2, 'name' => "Qatari rial" );
$currencies['RON'] = array ( 'code' => 946, 'decimal' => 2, 'name' => "Romanian new leu" );
$currencies['RSD'] = array ( 'code' => 941, 'decimal' => 2, 'name' => "Serbian dinar" );
$currencies['RUB'] = array ( 'code' => 643, 'decimal' => 2, 'name' => "Russian rouble" );
$currencies['RWF'] = array ( 'code' => 646, 'decimal' => 0, 'name' => "Rwanda franc" );
$currencies['SAR'] = array ( 'code' => 682, 'decimal' => 2, 'name' => "Saudi riyal" );
$currencies['SBD'] = array ( 'code' => 090, 'decimal' => 2, 'name' => "Solomon Islands dollar" );
$currencies['SCR'] = array ( 'code' => 690, 'decimal' => 2, 'name' => "Seychelles rupee" );
$currencies['SDG'] = array ( 'code' => 938, 'decimal' => 2, 'name' => "Sudanese pound" );
$currencies['SEK'] = array ( 'code' => 752, 'decimal' => 2, 'name' => "Swedish krona/kronor" );
$currencies['SGD'] = array ( 'code' => 702, 'decimal' => 2, 'name' => "Singapore dollar" );
$currencies['SHP'] = array ( 'code' => 654, 'decimal' => 2, 'name' => "Saint Helena pound" );
$currencies['SLL'] = array ( 'code' => 694, 'decimal' => 0, 'name' => "Leone" );
$currencies['SOS'] = array ( 'code' => 706, 'decimal' => 2, 'name' => "Somali shilling" );
$currencies['SRD'] = array ( 'code' => 968, 'decimal' => 2, 'name' => "Surinam dollar" );
$currencies['STD'] = array ( 'code' => 678, 'decimal' => 0, 'name' => "Dobra" );
$currencies['SYP'] = array ( 'code' => 760, 'decimal' => 2, 'name' => "Syrian pound" );
$currencies['SZL'] = array ( 'code' => 748, 'decimal' => 2, 'name' => "Lilangeni" );
$currencies['THB'] = array ( 'code' => 764, 'decimal' => 2, 'name' => "Baht" );
$currencies['TJS'] = array ( 'code' => 972, 'decimal' => 2, 'name' => "Somoni" );
$currencies['TMT'] = array ( 'code' => 934, 'decimal' => 2, 'name' => "Manat" );
$currencies['TND'] = array ( 'code' => 788, 'decimal' => 3, 'name' => "Tunisian dinar" );
$currencies['TOP'] = array ( 'code' => 776, 'decimal' => 2, 'name' => "Pa'anga" );
$currencies['TRY'] = array ( 'code' => 949, 'decimal' => 2, 'name' => "Turkish lira" );
$currencies['TTD'] = array ( 'code' => 780, 'decimal' => 2, 'name' => "Trinidad and Tobago dollar" );
$currencies['TWD'] = array ( 'code' => 901, 'decimal' => 1, 'name' => "New Taiwan dollar" );
$currencies['TZS'] = array ( 'code' => 834, 'decimal' => 2, 'name' => "Tanzanian shilling" );
$currencies['UAH'] = array ( 'code' => 980, 'decimal' => 2, 'name' => "Hryvnia" );
$currencies['UGX'] = array ( 'code' => 800, 'decimal' => 0, 'name' => "Uganda shilling" );
$currencies['USD'] = array ( 'code' => 840, 'decimal' => 2, 'name' => "US dollar" );
$currencies['USN'] = array ( 'code' => 997, 'decimal' => 2, 'name' => "United States dollar (next day) (funds code)" );
$currencies['USS'] = array ( 'code' => 998, 'decimal' => 2, 'name' => "United States dollar (same day) (funds code) (one source claims it is no longer used, but it is still on the ISO 4217-MA list)" );
$currencies['UYU'] = array ( 'code' => 858, 'decimal' => 2, 'name' => "Peso Uruguayo" );
$currencies['UZS'] = array ( 'code' => 860, 'decimal' => 2, 'name' => "Uzbekistan som" );
$currencies['VEF'] = array ( 'code' => 937, 'decimal' => 2, 'name' => "Venezuelan bolívar fuerte" );
$currencies['VND'] = array ( 'code' => 704, 'decimal' => 0, 'name' => "Vietnamese dong" );
$currencies['VUV'] = array ( 'code' => 548, 'decimal' => 0, 'name' => "Vatu" );
$currencies['WST'] = array ( 'code' => 882, 'decimal' => 2, 'name' => "Samoan tala" );
$currencies['XAF'] = array ( 'code' => 950, 'decimal' => 0, 'name' => "CFA franc BEAC" );
//$currencies['XAG'] = array ( 'code' => 961, 'decimal' => ., 'name' => "Silver (one troy ounce)" );
//$currencies['XAU'] = array ( 'code' => 959, 'decimal' => ., 'name' => "Gold (one troy ounce)" );
//$currencies['XBA'] = array ( 'code' => 955, 'decimal' => ., 'name' => "European Composite Unit (EURCO) (bond market unit)" );
//$currencies['XBB'] = array ( 'code' => 956, 'decimal' => ., 'name' => "European Monetary Unit (E.M.U.-6) (bond market unit)" );
//$currencies['XBC'] = array ( 'code' => 957, 'decimal' => ., 'name' => "European Unit of Account 9 (E.U.A.-9) (bond market unit)" );
//$currencies['XBD'] = array ( 'code' => 958, 'decimal' => ., 'name' => "European Unit of Account 17 (E.U.A.-17) (bond market unit)" );
$currencies['XCD'] = array ( 'code' => 951, 'decimal' => 2, 'name' => "East Caribbean dollar" );
//$currencies['XDR'] = array ( 'code' => 960, 'decimal' => ., 'name' => "Special Drawing Rights" );
//$currencies['XFU'] = array ( 'code' => Nil, 'decimal' => ., 'name' => "UIC franc (special settlement currency)" );
$currencies['XOF'] = array ( 'code' => 952, 'decimal' => 0, 'name' => "CFA Franc BCEAO" );
//$currencies['XPD'] = array ( 'code' => 964, 'decimal' => ., 'name' => "Palladium (one troy ounce)" );
$currencies['XPF'] = array ( 'code' => 953, 'decimal' => 0, 'name' => "CFP franc" );
//$currencies['XPT'] = array ( 'code' => 962, 'decimal' => ., 'name' => "Platinum (one troy ounce)" );
//$currencies['XTS'] = array ( 'code' => 963, 'decimal' => ., 'name' => "Code reserved for testing purposes" );
//$currencies['XXX'] = array ( 'code' => 999, 'decimal' => ., 'name' => "No currency" );
$currencies['YER'] = array ( 'code' => 886, 'decimal' => 0, 'name' => "Yemeni rial" );
$currencies['ZAR'] = array ( 'code' => 710, 'decimal' => 2, 'name' => "South African rand" );
$currencies['ZMK'] = array ( 'code' => 894, 'decimal' => 0, 'name' => "Kwacha" );
$currencies['ZWL'] = array ( 'code' => 932, 'decimal' => 2, 'name' => "Zimbabwe dollar" );