<?
require_once 'Criteria.php';
require_once 'PropelPager.php';
require_once 'AuthAccessPermissionsPeer.php';

/**
 * AuthAccessPermissions Business Model generated by Tlalokes Framework
 *
 * @author Tlalokes Framework
 */
class AuthAccessPermissionsBss {

  /**
   * Returns every elements
   *
   * @return mixed
   */
  public static function getByCtl ( $controller, $profile )
  {
    try {
      $c = new Criteria;
      $c->add( AuthAccessPermissionsPeer::CONTROLLER, $controller );
      $c->add( AuthAccessPermissionsPeer::PROFILE, $profile );

      $obj = AuthAccessPermissionsPeer::doSelectOne( $c );

      if ( !$obj ) {
        throw new Exception( "There is no controller $controller in profiles" );
      }

      return array( 'id' => $obj->getId(),
                    'profile' => $obj->getAuthAccessProfiles()->getId(),
                    'controller' => $obj->getController(),
                    'methods' => $obj->getMethods() );
    } catch ( Exception $e ) {
      return $e->getMessage();
    }
  }

  /**
   * Returns every elements
   *
   * @return mixed
   */
  public static function getAll ( TlalokesRequest &$request )
  {
    try {
      $page = isset( $request->page ) ? $request->page : 1;
      $limit = isset( $request->limit ) ? $request->limit : 0;
      if ( $page > 1 && $limit == 0 ) {
        throw new Exception( "There is no page $page" );
      }

      $pager = new PropelPager( null, 'AuthAccessPermissionsPeer', 'doSelect', $page, $limit );
      if ( !$pager->getResult() ) {
        throw new Exception( 'There is no data' );
      }

      $r['pager']['total_pages'] = $pager->getTotalPages();
      $r['pager']['total_records_count'] = $pager->getTotalRecordCount();
      $r['pager']['current'] = $pager->getPage();
      $r['pager']['next'] = $pager->getNext();
      $r['pager']['prev'] = $pager->getPrev();
      $r['pager']['limit'] = $limit;

      foreach ( $pager->getResult() as $obj ) {
        $r['data'][] = array( 'id' => $obj->getId(),
                              'profile' => $obj->getAuthAccessProfiles()->getName(),
                              'controller' => $obj->getController(),
                              'methods' => $obj->getMethods() );
      }

      return $r;
    } catch ( Exception $e ) {
      return $e->getMessage();
    }
  }

  /**
   * Returns the content of an element by it's primary key
   *
   * @return mixed
   */
  public static function getByPK ( $id )
  {
    try {
      $obj = AuthAccessPermissionsPeer::retrieveByPK( $id );
      if ( !$obj ) {
        throw new Exception( "There is no data with key $id" );
      }

      return array( 'id' => $obj->getId(),
                    'profile' => $obj->getAuthAccessProfiles()->getName(),
                    'controller' => $obj->getController(),
                    'methods' => $obj->getMethods() );
    } catch ( Exception $e ) {
      return $e->getMessage();
    }
  }

  /**
   * Saves a new element
   *
   * @return mixed
   */
  public static function create ( TlalokesRequest &$request )
  {
    try {
      $obj = new AuthAccessPermissions;
      if ( isset( $request->id ) && $request->id ) {
        $obj->setId( $request->id );
      }
      if ( !isset( $request->profile ) || !$request->profile ) {
        throw new Exception( 'Provide a profile' );
      }
      if ( !isset( $request->controller ) || !$request->controller ) {
        throw new Exception( 'Provide a controller' );
      }
      if ( !isset( $request->methods ) || !$request->methods ) {
        throw new Exception( 'Provide one or more methods' );
      }
      $obj->setProfile( $request->profile );
      $obj->setController( $request->controller );
      $obj->setMethods( $request->methods );
      $obj->save();

      return self::getByPK( $obj->getId() );
    } catch ( PropelException $e ) {
      return preg_replace('/\	/','',tlalokes_str_sanitize($e->getMessage()));
    }
  }

  /**
   * Updates an element
   *
   * @return mixed
   */
  public static function update ( TlalokesRequest &$request )
  {
    try {
      $obj = AuthAccessPermissionsPeer::retrieveByPK( $request->_id );
      if ( isset( $request->id ) && $request->id ) {
        $obj->setId( $request->id );
      }
      if ( !isset( $request->profile ) || !$request->profile ) {
        throw new Exception( 'Provide a profile' );
      }
      if ( !isset( $request->controller ) || !$request->controller ) {
        throw new Exception( 'Provide a controller' );
      }
      if ( !isset( $request->methods ) || !$request->methods ) {
        throw new Exception( 'Provide one or more methods' );
      }
      $obj->setProfile( $request->profile );
      $obj->setController( $request->controller );
      $obj->setMethods( $request->methods );
      $obj->save();

      return self::getByPK( $obj->getId() );
    } catch ( PropelException $e ) {
      return preg_replace('/\	/','',tlalokes_str_sanitize( $e->getMessage() ));
    }
  }

  /**
   * Deletes an element
   *
   * @return mixed
   */
  public static function delete ( TlalokesRequest &$request )
  {
    try {
      AuthAccessPermissionsPeer::doDelete( $request->_id );

      return self::getAll( $request );
    } catch ( PropelException $e ) {
      return preg_replace('/\	/','',tlalokes_str_sanitize( $e->getMessage() ));
    }
  }

  /**
   * Returns an element filtering its contents
   *
   * @return mixed
   */
  public static function filter ( TlalokesRequest &$request )
  {
    try {
      $page = isset( $request->page ) ? $request->page : 1;
      $limit = isset( $request->limit ) ? $request->limit : 0;

      // set Criteria object
      $c = new Criteria();
      $c->setIgnoreCase( true );

      // add elements to criteria
      if ( $request->id ) {
        $c->add( AuthAccessPermissionsPeer::ID, $request->id, Criteria::EQUAL );
      }
      if ( $request->profile ) {
        $c->add( AuthAccessPermissionsPeer::PROFILE, $request->profile, Criteria::EQUAL );
      }
      if ( $request->controller ) {
        $c->add( AuthAccessPermissionsPeer::CONTROLLER, "%{$request->controller}%", Criteria::LIKE );
      }
      if ( $request->methods ) {
        $c->add( AuthAccessPermissionsPeer::METHODS, "%{$request->methods}%", Criteria::LIKE );
      }

      if ( $page > 1 && $limit == 0 ) {
        throw new Exception( "There is no page $page" );
      }

      $pager = new PropelPager( $c, 'AuthAccessPermissionsPeer', 'doSelect', $page, $limit );
      if ( !$pager->getResult() ) {
        throw new Exception( 'There are no coincidences' );
      }

      $r['pager']['total_pages'] = $pager->getTotalPages();
      $r['pager']['total_records_count'] = $pager->getTotalRecordCount();
      $r['pager']['current'] = $pager->getPage();
      $r['pager']['next'] = $pager->getNext();
      $r['pager']['prev'] = $pager->getPrev();
      $r['pager']['limit'] = $limit;

      foreach ( $pager->getResult() as $obj ) {
        $r['data'][] = array( 'id' => $obj->getId(),
                              'profile' => $obj->getAuthAccessProfiles()->getName(),
                              'controller' => $obj->getController(),
                              'methods' => $obj->getMethods() );
      }

      return $r;
    } catch ( Exception $e ) {
      return $e->getMessage();
    }
  }
}
