<?
require_once 'TlalokesCoreController.php';

/**
 * AuthAccessProfilesRoles Controller generated by Tlalokes Framework
 *
 * @author Tlalokes Framework
 * @ControllerDefinition( default='read', auth )
 */
class AuthAccessProfilesRolesCtl extends TlalokesCoreController {

  /**
   * Reads AuthAccessProfilesRoles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_roles_display;', propel )
   */
  public function read ()
  {
    if ( isset( $this->request->_id ) && $this->request->_id ) {
      $this->response->_id = $this->request->_id;
      $response = AuthAccessProfilesRolesBss::getByPK( $this->request->_id );
      if ( is_array( $response ) ) {
        $this->response->element = $response;
      } else {
        $this->response->exception = $response;
      }
    } else {
      $response = AuthAccessProfilesRolesBss::getAll( $this->request );
      if ( is_array( $response['data'] ) ) {
        $this->response->pager = $response['pager'];
        $this->response->list = $response['data'];
        // get reference's content for auth_access_profiles
        $auth_access_profiles = AuthAccessProfilesBss::getAll( $this->request );
        $this->response->auth_access_profiles = $auth_access_profiles['data'];
        // get reference's content for auth_roles
        $auth_roles = AuthRolesBss::getAll( $this->request );
        $this->response->auth_roles = $auth_roles['data'];
      } else {
        $this->response->exception = $response;
      }
    }
  }

  /**
   * Create AuthAccessProfilesRoles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_roles_display;', propel )
   */
  public function create ()
  {
    $response = AuthAccessProfilesRolesBss::create( $this->request );
    if ( is_array( $response ) ) {
      $this->response->_id = $response['id'];
      $this->response->element = $response;
    } else {
      $this->response->exception = $response;
    }
  }


  /**
   * Update AuthAccessProfilesRoles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_roles_display;', propel )
   */
  public function update ()
  {
    $response = AuthAccessProfilesRolesBss::update( $this->request );
    if ( is_array( $response ) ) {
      $this->response->_id = $response['id'];
      $this->response->element = $response;
    } else {
      $this->response->exception = $response;
    }
  }


  /**
   * Delete AuthAccessProfilesRoles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_roles_display;', propel )
   */
  public function delete ()
  {
    $response = AuthAccessProfilesRolesBss::delete( $this->request );
    if ( is_array( $response['data'] ) ) {
      $this->response->pager = $response['pager'];
      $this->response->list = $response['data'];
    } else {
      $this->response->exception = $response;
    }
  }

  /**
   * Add AuthAccessProfilesRoles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_roles_add;', propel )
   */
  public function add ()
  {    // get reference's content for auth_access_profiles
    $auth_access_profiles = AuthAccessProfilesBss::getAll( $this->request );
    $this->response->auth_access_profiles = $auth_access_profiles['data'];
    // get reference's content for auth_roles
    $auth_roles = AuthRolesBss::getAll( $this->request );
    $this->response->auth_roles = $auth_roles['data'];
  }


  /**
   * Edit AuthAccessProfilesRoles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_roles_edit;', propel )
   */
  public function edit ()
  {
    $this->response->_id = $this->request->_id;
    $response = AuthAccessProfilesRolesBss::getByPK( $this->request->_id );
    if ( is_array( $response ) ) {
      $this->add();
      $this->response->element = $response;
      // get reference's content for auth_access_profiles
      $auth_access_profiles = AuthAccessProfilesBss::getAll( $this->request );
      $this->response->auth_access_profiles = $auth_access_profiles['data'];
      // get reference's content for auth_roles
      $auth_roles = AuthRolesBss::getAll( $this->request );
      $this->response->auth_roles = $auth_roles['data'];
    } else {
      $this->response->exception = $response;
    }
  }

  /**
   * Filter AuthAccessProfilesRoles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_roles_display;', propel )
   */
  public function filter ()
  {
    $response = AuthAccessProfilesRolesBss::filter( $this->request );
    if ( is_array( $response ) ) {
      $this->response->vars = $_SERVER['QUERY_STRING'];
      $this->response->pager = $response['pager'];
      $this->response->list = $response['data'];
      // get reference's content for auth_access_profiles
      $auth_access_profiles = AuthAccessProfilesBss::getAll( $this->request );
      $this->response->auth_access_profiles = $auth_access_profiles['data'];
      // get reference's content for auth_roles
      $auth_roles = AuthRolesBss::getAll( $this->request );
      $this->response->auth_roles = $auth_roles['data'];
    } else {
      $this->response->exception = $response;
      $list = AuthAccessProfilesRolesBss::getAll( $this->request );
      $this->response->list = $list['pager'];
      $this->response->data = $list['data'];
    }
  }
}
