<?
require_once 'TlalokesCoreController.php';

/**
 * AuthAccessProfiles Controller generated by Tlalokes Framework
 *
 * @author Tlalokes Framework
 * @ControllerDefinition( default='read', auth )
 */
class AuthAccessProfilesCtl extends TlalokesCoreController {

  /**
   * Reads AuthAccessProfiles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_display;', propel )
   */
  public function read ()
  {
    if ( isset( $this->request->_id ) && $this->request->_id ) {
      $this->response->_id = $this->request->_id;
      $response = AuthAccessProfilesBss::getByPK( $this->request->_id );
      if ( is_array( $response ) ) {
        $this->response->element = $response;
      } else {
        $this->response->exception = $response;
      }
    } else {
      $response = AuthAccessProfilesBss::getAll( $this->request );
      if ( is_array( $response['data'] ) ) {
        $this->response->pager = $response['pager'];
        $this->response->list = $response['data'];
      } else {
        $this->response->exception = $response;
      }
    }
  }

  /**
   * Create AuthAccessProfiles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_display;', propel )
   */
  public function create ()
  {
    $response = AuthAccessProfilesBss::create( $this->request );
    if ( is_array( $response ) ) {
      $this->response->_id = $response['id'];
      $this->response->element = $response;
    } else {
      $this->response->exception = $response;
    }
  }


  /**
   * Update AuthAccessProfiles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_display;', propel )
   */
  public function update ()
  {
    $response = AuthAccessProfilesBss::update( $this->request );
    if ( is_array( $response ) ) {
      $this->response->_id = $response['id'];
      $this->response->element = $response;
    } else {
      $this->response->exception = $response;
    }
  }


  /**
   * Delete AuthAccessProfiles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_display;', propel )
   */
  public function delete ()
  {
    $response = AuthAccessProfilesBss::delete( $this->request );
    if ( is_array( $response['data'] ) ) {
      $this->response->pager = $response['pager'];
      $this->response->list = $response['data'];
    } else {
      $this->response->exception = $response;
    }
  }

  /**
   * Add AuthAccessProfiles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_add;', propel )
   */
  public function add ()
  {  }


  /**
   * Edit AuthAccessProfiles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_edit;', propel )
   */
  public function edit ()
  {
    $this->response->_id = $this->request->_id;
    $response = AuthAccessProfilesBss::getByPK( $this->request->_id );
    if ( is_array( $response ) ) {
      $this->add();
      $this->response->element = $response;
    } else {
      $this->response->exception = $response;
    }
  }

  /**
   * Filter AuthAccessProfiles
   *
   * @ActionDefinition( layout='auth_layout.tpl', zone='content:access_profiles_display;', propel )
   */
  public function filter ()
  {
    $response = AuthAccessProfilesBss::filter( $this->request );
    if ( is_array( $response ) ) {
      $this->response->vars = $_SERVER['QUERY_STRING'];
      $this->response->pager = $response['pager'];
      $this->response->list = $response['data'];
    } else {
      $this->response->exception = $response;
      $list = AuthAccessProfilesBss::getAll( $this->request );
      $this->response->list = $list['pager'];
      $this->response->data = $list['data'];
    }
  }
}
